// src/app/pages/cadastro/cadastro.component.ts
import { Component, inject } from '@angular/core';
import { Router } from '@angular/router';
import { CommonModule } from '@angular/common';
import { FormsModule } from '@angular/forms';
import { SecurityBadgesComponent } from '../../components/security-badges/security-badges.component';
import { AuthApiService } from '../../core/services/api/auth-api.service';

@Component({
  selector: 'app-cadastro',
  standalone: true,
  imports: [CommonModule, FormsModule, SecurityBadgesComponent],
  templateUrl: './cadastro.component.html',
  styleUrls: ['./cadastro.component.css']
})
export class CadastroComponent {
  private router = inject(Router);
  private authApi = inject(AuthApiService);

  showPassword = false;
  
  nome = '';
  crm = '';
  especialidade = '';
  email = '';
  senha = '';

  togglePasswordVisibility() {
    this.showPassword = !this.showPassword;
  }

  handleSubmit(e: Event) {
    e.preventDefault();
  }

  async handleCadastro(e: Event) {
    e.preventDefault();
    if (!this.nome || !this.email || !this.senha || !this.crm || !this.especialidade) return;

    const req = {
      nome: this.nome,
      crm: this.crm,
      especialidade: this.especialidade,
      email: this.email,
      senha: this.senha
    };

    try {
      await this.authApi.cadastrar(req).toPromise();
      this.router.navigate(['/login']);
    } catch (error) {
      console.error(error);
    }
  }

  navigate(path: string) {
    this.router.navigate([path]);
  }
}

<div class="cadastro-card-container">
  <div class="cadastro-card">
    <div class="cadastro-header">
      <h1>Cadastro Médico</h1>
      <p>Crie sua conta profissional no Tila para gerar laudos automatizados.</p>
    </div>

    <!-- warning message placeholder missing in react, but I will keep structure identical -->

    <form (submit)="handleSubmit($event)" class="cadastro-form">
      <div class="form-group">
        <label for="nome">Nome Completo</label>
        <input
          type="text"
          id="nome"
          placeholder="Dr. João da Silva"
          class="form-input"
          [(ngModel)]="nome"
          name="nome"
        />
      </div>

      <div class="form-row">
        <div class="form-group flex-1">
          <label for="crm">CRM</label>
          <input
            type="text"
            id="crm"
            placeholder="000000-SP"
            class="form-input"
            [(ngModel)]="crm"
            name="crm"
          />
        </div>

        <div class="form-group flex-1">
          <label for="especialidade">Especialidade</label>
          <input
            type="text"
            id="especialidade"
            placeholder="Radiologia"
            class="form-input"
            [(ngModel)]="especialidade"
            name="especialidade"
          />
        </div>
      </div>

      <div class="form-group">
        <label for="email">E-mail Profissional</label>
        <input
          type="email"
          id="email"
          placeholder="medico@clinica.com"
          class="form-input"
          [(ngModel)]="email"
          name="email"
        />
      </div>

      <div class="form-group">
        <label for="password">Senha</label>
        <div class="password-input-wrapper">
          <input
            [type]="showPassword ? 'text' : 'password'"
            id="password"
            placeholder="••••••••"
            class="form-input password-input"
            [(ngModel)]="senha"
            name="senha"
          />
          <button
            type="button"
            class="toggle-password-btn"
            (click)="togglePasswordVisibility()"
            aria-label="Toggle password visibility"
          >
            <span class="material-icons">{{ showPassword ? 'visibility_off' : 'visibility' }}</span>
          </button>
        </div>
      </div>

      <button type="submit" class="submit-btn cadastro-submit-btn" (click)="handleCadastro($event)">
        <span class="material-icons btn-icon">person_add</span>
        Criar Conta
      </button>

      <div class="auth-switch-container">
        <span class="auth-switch-text">Já possui uma conta?</span>
        <button type="button" (click)="navigate('/login')" class="auth-switch-btn">
          Faça login
        </button>
      </div>
    </form>

    <app-security-badges></app-security-badges>
  </div>
</div>

// src/pages/Cadastro/Cadastro.jsx
import React, { useState } from 'react';
import { useNavigate } from 'react-router-dom';
import { MdVisibility, MdVisibilityOff, MdPersonAdd } from 'react-icons/md';
import SecurityBadges from '../../components/SecurityBadges/SecurityBadges';
import './Cadastro.css';
import { apiCadastro } from '../../api/cadastro/apiCadastro'

const Cadastro = () => {
  const navigate = useNavigate();
  const [showPassword, setShowPassword] = useState(false);

  const togglePasswordVisibility = () => {
    setShowPassword(!showPassword);
  };

  const handleSubmit = (e) => {
    e.preventDefault();
  };

  const handleCadastro = () => {
    const req = {
      nome: document.getElementById('nome').value,
      crm: document.getElementById('crm').value,
      especialidade: document.getElementById('especialidade').value,
      email: document.getElementById('email').value,
      senha: document.getElementById('password').value,
    };
    apiCadastro.cadastrar(req);
    navigate('/login');
  }

  return (
    <div className="cadastro-card-container">
      <div className="cadastro-card">
        <div className="cadastro-header">
          <h1>Cadastro Médico</h1>
          <p>Crie sua conta profissional no Tila para gerar laudos automatizados.</p>
        </div>

        <form onSubmit={handleSubmit} className="cadastro-form">
          <div className="form-group">
            <label htmlFor="nome">Nome Completo</label>
            <input
              type="text"
              id="nome"
              placeholder="Dr. João da Silva"
              className="form-input"
            />
          </div>

          <div className="form-row">
            <div className="form-group flex-1">
              <label htmlFor="crm">CRM</label>
              <input
                type="text"
                id="crm"
                placeholder="000000-SP"
                className="form-input"
              />
            </div>

            <div className="form-group flex-1">
              <label htmlFor="especialidade">Especialidade</label>
              <input
                type="text"
                id="especialidade"
                placeholder="Radiologia"
                className="form-input"
              />
            </div>
          </div>

          <div className="form-group">
            <label htmlFor="email">E-mail Profissional</label>
            <input
              type="email"
              id="email"
              placeholder="medico@clinica.com"
              className="form-input"
            />
          </div>

          <div className="form-group">
            <label htmlFor="password">Senha</label>
            <div className="password-input-wrapper">
              <input
                type={showPassword ? 'text' : 'password'}
                id="password"
                placeholder="••••••••"
                className="form-input password-input"
              />
              <button
                type="button"
                className="toggle-password-btn"
                onClick={togglePasswordVisibility}
                aria-label="Toggle password visibility"
              >
                {showPassword ? <MdVisibilityOff /> : <MdVisibility />}
              </button>
            </div>
          </div>

          <button type="submit" className="submit-btn cadastro-submit-btn" onClick={handleCadastro}>
            <MdPersonAdd className="btn-icon" />
            Criar Conta
          </button>

          <div className="auth-switch-container">
            <span className="auth-switch-text">Já possui uma conta?</span>
            <button type="button" onClick={() => navigate('/login')} className="auth-switch-btn">
              Faça login
            </button>
          </div>
        </form>

        <SecurityBadges />
      </div>
    </div>
  );
};

export default Cadastro;
