// src/app/pages/dashboard/dashboard.component.ts
import { Component, inject, OnInit } from '@angular/core';
import { CommonModule } from '@angular/common';
import { RouterLink } from '@angular/router';
import { AuthStore } from '../../core/services/store/auth.store';

@Component({
  selector: 'app-dashboard',
  standalone: true,
  imports: [CommonModule, RouterLink],
  templateUrl: './dashboard.component.html',
  styleUrls: ['./dashboard.component.css']
})
export class DashboardComponent implements OnInit {
  private authStore = inject(AuthStore);
  
  isSidebarOpen = false;
  user = this.authStore.user;
  //função para logar quando iniciar a tela de dashboar
  ngOnInit() {
    this.logarnoConsole();
  }
  private logarnoConsole() {
    console.log("dados do storage", this.user());
  }
  
  today = new Date().toLocaleDateString('pt-BR');

  setIsSidebarOpen(isOpen: boolean) {
    this.isSidebarOpen = isOpen;
  }
}

<div class="dashboard-container">
  <!-- Mobile Sidebar Overlay -->
  @if (isSidebarOpen) {
    <div class="sidebar-overlay" (click)="setIsSidebarOpen(false)"></div>
  }

  <!-- Sidebar -->
  <aside class="dashboard-sidebar" [class.open]="isSidebarOpen">
    <div class="sidebar-header">
      <div class="sidebar-logo">
        <svg width="24" height="24" viewBox="0 0 24 24" fill="none" class="logo-icon">
          <path d="M12 2L2 12l10 10 10-10L12 2z" fill="currentColor" />
          <path d="M12 2L2 12l10 10V2z" fill="#0b57d0" />
          <path d="M12 2l10 10-10 10V2z" fill="#1a73e8" />
        </svg>
        <span class="logo-text">Tila Medical</span>
      </div>
    </div>

    <nav class="sidebar-nav">
      <ul class="nav-list">
        <li class="nav-item active" routerLink="/dashboard">
          <span class="material-icons nav-icon">dashboard</span>
          <span>Painel</span>
        </li>
        <li class="nav-item" routerLink="/pacientes">
          <span class="material-icons nav-icon">people</span>
          <span>Pacientes</span>
        </li>
        <li class="nav-item">
          <span class="material-icons nav-icon">description</span>
          <span>Laudos</span>
        </li>
        <li class="nav-item">
          <span class="material-icons nav-icon">calendar_today</span>
          <span>Agenda</span>
        </li>
      </ul>
    </nav>

    <div class="sidebar-footer">
      <div class="nav-item settings-item">
        <span class="material-icons nav-icon">settings</span>
        <span>Configurações</span>
      </div>
      <div class="user-profile">
        <div class="user-avatar">
          <img src="https://ui-avatars.com/api/?name=Julian+Smith&background=0D8ABC&color=fff" alt="Dr. Avatar" />
        </div>
        <div class="user-info">
          <span class="user-name">{{ user()?.nomeCompleto }}</span>
          <span class="user-role">{{ user()?.especialidade }}</span>
        </div>
      </div>
    </div>
  </aside>

  <!-- Main Content Area -->
  <div class="dashboard-main">
    <!-- Top Header -->
    <header class="dashboard-header">
      <div class="header-left">
        <button class="mobile-menu-btn" (click)="setIsSidebarOpen(true)" aria-label="Abrir Menu">
          <span class="material-icons">menu</span>
        </button>
        <div class="search-bar">
          <span class="material-icons search-icon">search</span>
          <input type="text" placeholder="Busca rápida de paciente..." />
        </div>
      </div>
      <div class="header-actions">
        <div class="notification-bell">
          <span class="material-icons bell-icon">notifications</span>
          <span class="notification-dot"></span>
        </div>
        <button class="btn-primary">
          <span class="material-icons btn-icon">add</span>
          <span class="btn-text">Novo Laudo</span>
        </button>
      </div>
    </header>

    <!-- Dashboard Content -->
    <main class="dashboard-content">
      <div class="page-title">
        <h1>Painel do Médico</h1>
        <p>Bem-vindo de volta, Dr. {{ user()?.nomeCompleto }}. Aqui está sua visão geral de hoje, {{ today }}.</p>
      </div>

      <!-- Summary Cards -->
      <div class="summary-cards">
        <div class="summary-card">
          <div class="card-header">
            <span class="card-title">Laudos Este Mês</span>
            <span class="material-icons card-icon blue-icon">description</span>
          </div>
          <div class="card-body">
            <span class="card-value">0</span>
          </div>
        </div>

        <div class="summary-card">
          <div class="card-header">
            <span class="card-title">Revisões Pendentes</span>
            <span class="material-icons card-icon orange-icon">dashboard</span>
          </div>
          <div class="card-body">
            <span class="card-value">0</span>
          </div>
        </div>

        <div class="summary-card">
          <div class="card-header">
            <span class="card-title">Agendamentos</span>
            <span class="material-icons card-icon blue-icon">calendar_today</span>
          </div>
          <div class="card-body">
            <span class="card-value">0</span>
          </div>
        </div>
      </div>

      <div class="dashboard-grid">
        <!-- Left Column -->
        <div class="grid-left">
          <!-- Exames Pendentes -->
          <div class="content-panel">
            <div class="panel-header">
              <h2>Exames Pendentes de Revisão</h2>
              <a href="#todos" class="view-all-link">Ver Todos</a>
            </div>
            <div class="table-container">
              <table class="pending-table">
                <thead>
                  <tr>
                    <th>PACIENTE</th>
                    <th>TIPO DE EXAME</th>
                    <th>AÇÕES</th>
                  </tr>
                </thead>
                <tbody>
                  <tr>
                    <td>
                      <div class="patient-info">
                        <span class="patient-name">Sarah Jenkins</span>
                        <span class="patient-id">ID: #882193</span>
                      </div>
                    </td>
                    <td>Raio-X de Tórax (PA)</td>
                    <td><button class="btn-action">Revisar</button></td>
                  </tr>
                  <tr>
                    <td>
                      <div class="patient-info">
                        <span class="patient-name">Robert Miller</span>
                        <span class="patient-id">ID: #881204</span>
                      </div>
                    </td>
                    <td>RM de Crânio c/ Contraste</td>
                    <td><button class="btn-action">Revisar</button></td>
                  </tr>
                  <tr>
                    <td>
                      <div class="patient-info">
                        <span class="patient-name">Elena Rodriguez</span>
                        <span class="patient-id">ID: #883011</span>
                      </div>
                    </td>
                    <td>TC de Abdome/Pelve</td>
                    <td><button class="btn-action">Revisar</button></td>
                  </tr>
                </tbody>
              </table>
            </div>
          </div>

          <!-- Laudos Finalizados Recentemente -->
          <div class="content-panel mt-4">
            <div class="panel-header">
              <h2>Laudos Finalizados Recentemente</h2>
            </div>
            <div class="recent-reports">
              <div class="report-card">
                <div class="report-icon-wrapper">
                  <svg width="24" height="24" viewBox="0 0 24 24" fill="none" class="report-icon">
                    <path d="M19 3H5c-1.1 0-2 .9-2 2v14c0 1.1.9 2 2 2h14c1.1 0 2-.9 2-2V5c0-1.1-.9-2-2-2zm-9.5 8.5H8v1h1.5c.28 0 .5.22.5.5v1.5c0 .28-.22.5-.5.5H8v1H6.5v-6h3c.28 0 .5.22.5.5v1.5c0 .28-.22.5-.5.5zm4.5 1.5H12v-1h2c.28 0 .5-.22.5-.5V10c0-.28-.22-.5-.5-.5h-3v6h1.5v-2h1.5c.28 0 .5-.22.5-.5v-1c0-.28-.22-.5-.5-.5zm4-3.5h-3v6h1.5v-2h1.5v-1.5h-1.5v-1h1.5V9.5z" fill="#0b57d0" />
                    <path d="M8 10.5h1v1H8v-1zm4.5 0h1v2h-1v-2z" fill="#0b57d0" />
                  </svg>
                </div>
                <div class="report-info">
                  <span class="report-title">Seguimento de Nó...</span>
                  <span class="report-meta">Assinado há 2h • Finalizado</span>
                </div>
                <span class="material-icons report-arrow">keyboard_arrow_right</span>
              </div>

              <div class="report-card">
                <div class="report-icon-wrapper">
                  <svg width="24" height="24" viewBox="0 0 24 24" fill="none" class="report-icon">
                    <path d="M19 3H5c-1.1 0-2 .9-2 2v14c0 1.1.9 2 2 2h14c1.1 0 2-.9 2-2V5c0-1.1-.9-2-2-2zm-9.5 8.5H8v1h1.5c.28 0 .5.22.5.5v1.5c0 .28-.22.5-.5.5H8v1H6.5v-6h3c.28 0 .5.22.5.5v1.5c0 .28-.22.5-.5.5zm4.5 1.5H12v-1h2c.28 0 .5-.22.5-.5V10c0-.28-.22-.5-.5-.5h-3v6h1.5v-2h1.5c.28 0 .5-.22.5-.5v-1c0-.28-.22-.5-.5-.5zm4-3.5h-3v6h1.5v-2h1.5v-1.5h-1.5v-1h1.5V9.5z" fill="#0b57d0" />
                    <path d="M8 10.5h1v1H8v-1zm4.5 0h1v2h-1v-2z" fill="#0b57d0" />
                  </svg>
                </div>
                <div class="report-info">
                  <span class="report-title">Fratura de Mão - M...</span>
                  <span class="report-meta">Assinado há 4h • Finalizado</span>
                </div>
                <span class="material-icons report-arrow">keyboard_arrow_right</span>
              </div>
            </div>
          </div>
        </div>

        <!-- Right Column -->
        <div class="grid-right">
          <!-- Ações Rápidas -->
          <div class="content-panel quick-actions-panel">
            <h2>Ações Rápidas</h2>
            <div class="quick-action-btns">
              <button class="btn-action-large primary">
                <span class="material-icons btn-icon">add</span>
                Novo Laudo
              </button>
              <button class="btn-action-large secondary">
                <span class="material-icons btn-icon">library_books</span>
                Prontuários
              </button>
              <button class="btn-action-large secondary">
                <span class="material-icons btn-icon">layers</span>
                Modelos de Laudo
              </button>
            </div>
          </div>

          <!-- Modelos Favoritos -->
          <div class="content-panel mt-4">
            <h2>Modelos Favoritos</h2>
            <div class="favorites-list mt-3">
              <p class="favorites-placeholder">Em breve modelos de laudos!</p>
            </div>
          </div>
        </div>
      </div>
    </main>
  </div>
</div>

// src/pages/Dashboard/Dashboard.jsx
import React, { useState } from 'react';
import { useNavigate } from 'react-router-dom';
import {
  MdDashboard,
  MdPeople,
  MdDescription,
  MdAutoGraph,
  MdCalendarToday,
  MdSettings,
  MdSearch,
  MdNotifications,
  MdAdd,
  MdKeyboardArrowRight,
  MdLibraryBooks,
  MdLayers,
  MdAutoAwesome,
  MdMenu,
  MdClose
} from 'react-icons/md';
import './Dashboard.css';
import { useAuthStore } from '../../store/useAuthStore';

const Dashboard = () => {
  const navigate = useNavigate();
  const [isSidebarOpen, setIsSidebarOpen] = useState(false);
  const user = useAuthStore((state) => state.user);

  return (
    <div className="dashboard-container">
      {/* Mobile Sidebar Overlay */}
      {isSidebarOpen && (
        <div
          className="sidebar-overlay"
          onClick={() => setIsSidebarOpen(false)}
        ></div>
      )}

      {/* Sidebar */}
      <aside className={`dashboard-sidebar ${isSidebarOpen ? 'open' : ''}`}>
        <div className="sidebar-header">
          <div className="sidebar-logo">
            <svg width="24" height="24" viewBox="0 0 24 24" fill="none" xmlns="http://www.w3.org/2000/svg" className="logo-icon">
              <path d="M12 2L2 12l10 10 10-10L12 2z" fill="currentColor" />
              <path d="M12 2L2 12l10 10V2z" fill="#0b57d0" />
              <path d="M12 2l10 10-10 10V2z" fill="#1a73e8" />
            </svg>
            <span className="logo-text">Tila Medical</span>
          </div>
        </div>

        <nav className="sidebar-nav">
          <ul className="nav-list">
            <li className="nav-item active" onClick={() => navigate('/dashboard')}>
              <MdDashboard className="nav-icon" />
              <span>Painel</span>
            </li>
            <li className="nav-item" onClick={() => navigate('/pacientes')}>
              <MdPeople className="nav-icon" />
              <span>Pacientes</span>
            </li>
            <li className="nav-item">
              <MdDescription className="nav-icon" />
              <span>Laudos</span>
            </li>
            <li className="nav-item">
              <MdCalendarToday className="nav-icon" />
              <span>Agenda</span>
            </li>
          </ul>
        </nav>

        <div className="sidebar-footer">
          <div className="nav-item settings-item">
            <MdSettings className="nav-icon" />
            <span>Configurações</span>
          </div>
          <div className="user-profile">
            <div className="user-avatar">
              <img src="https://ui-avatars.com/api/?name=Julian+Smith&background=0D8ABC&color=fff" alt="Dr. Julian Smith" />
            </div>
            <div className="user-info">
              <span className="user-name">{user?.nomeCompleto}</span>
              <span className="user-role">{user?.especialidade}</span>
            </div>
          </div>
        </div>
      </aside>

      {/* Main Content Area */}
      <div className="dashboard-main">
        {/* Top Header */}
        <header className="dashboard-header">
          <div className="header-left">
            <button
              className="mobile-menu-btn"
              onClick={() => setIsSidebarOpen(true)}
              aria-label="Abrir Menu"
            >
              <MdMenu />
            </button>
            <div className="search-bar">
              <MdSearch className="search-icon" />
              <input type="text" placeholder="Busca rápida de paciente..." />
            </div>
          </div>
          <div className="header-actions">
            <div className="notification-bell">
              <MdNotifications className="bell-icon" />
              <span className="notification-dot"></span>
            </div>
            <button className="btn-primary">
              <MdAdd className="btn-icon" />
              <span className="btn-text">Novo Laudo</span>
            </button>
          </div>
        </header>

        {/* Dashboard Content */}
        <main className="dashboard-content">
          <div className="page-title">
            <h1>Painel do Médico</h1>
            <p>Bem-vindo de volta, Dr. {user?.nomeCompleto}. Aqui está sua visão geral de hoje, {new Date().toLocaleDateString()}.</p>
          </div>

          {/* Summary Cards */}
          <div className="summary-cards">
            {/* Card 1 */}
            <div className="summary-card">
              <div className="card-header">
                <span className="card-title">Laudos Este Mês</span>
                <MdDescription className="card-icon blue-icon" />
              </div>
              <div className="card-body">
                <span className="card-value">0</span>
              </div>
            </div>

            {/* Card 3 */}
            <div className="summary-card">
              <div className="card-header">
                <span className="card-title">Revisões Pendentes</span>
                <MdDashboard className="card-icon orange-icon" />
              </div>
              <div className="card-body">
                <span className="card-value">0</span>
              </div>
            </div>

            {/* Card 4 */}
            <div className="summary-card">
              <div className="card-header">
                <span className="card-title">Agendamentos</span>
                <MdCalendarToday className="card-icon blue-icon" />
              </div>
              <div className="card-body">
                <span className="card-value">0</span>
              </div>
            </div>
          </div>

          <div className="dashboard-grid">
            {/* Left Column */}
            <div className="grid-left">
              {/* Exames Pendentes */}
              <div className="content-panel">
                <div className="panel-header">
                  <h2>Exames Pendentes de Revisão</h2>
                  <a href="#todos" className="view-all-link">Ver Todos</a>
                </div>
                <div className="table-container">
                  <table className="pending-table">
                    <thead>
                      <tr>
                        <th>PACIENTE</th>
                        <th>TIPO DE EXAME</th>
                        <th>AÇÕES</th>
                      </tr>
                    </thead>
                    <tbody>
                      <tr>
                        <td>
                          <div className="patient-info">
                            <span className="patient-name">Sarah Jenkins</span>
                            <span className="patient-id">ID: #882193</span>
                          </div>
                        </td>
                        <td>Raio-X de Tórax (PA)</td>
                        <td><button className="btn-action">Revisar</button></td>
                      </tr>
                      <tr>
                        <td>
                          <div className="patient-info">
                            <span className="patient-name">Robert Miller</span>
                            <span className="patient-id">ID: #881204</span>
                          </div>
                        </td>
                        <td>RM de Crânio c/ Contraste</td>
                        <td><button className="btn-action">Revisar</button></td>
                      </tr>
                      <tr>
                        <td>
                          <div className="patient-info">
                            <span className="patient-name">Elena Rodriguez</span>
                            <span className="patient-id">ID: #883011</span>
                          </div>
                        </td>
                        <td>TC de Abdome/Pelve</td>
                        <td><button className="btn-action">Revisar</button></td>
                      </tr>
                    </tbody>
                  </table>
                </div>
              </div>

              {/* Laudos Finalizados Recentemente */}
              <div className="content-panel mt-4">
                <div className="panel-header">
                  <h2>Laudos Finalizados Recentemente</h2>
                </div>
                <div className="recent-reports">
                  <div className="report-card">
                    <div className="report-icon-wrapper">
                      <svg width="24" height="24" viewBox="0 0 24 24" fill="none" className="report-icon">
                        <path d="M19 3H5c-1.1 0-2 .9-2 2v14c0 1.1.9 2 2 2h14c1.1 0 2-.9 2-2V5c0-1.1-.9-2-2-2zm-9.5 8.5H8v1h1.5c.28 0 .5.22.5.5v1.5c0 .28-.22.5-.5.5H8v1H6.5v-6h3c.28 0 .5.22.5.5v1.5c0 .28-.22.5-.5.5zm4.5 1.5H12v-1h2c.28 0 .5-.22.5-.5V10c0-.28-.22-.5-.5-.5h-3v6h1.5v-2h1.5c.28 0 .5-.22.5-.5v-1c0-.28-.22-.5-.5-.5zm4-3.5h-3v6h1.5v-2h1.5v-1.5h-1.5v-1h1.5V9.5z" fill="#0b57d0" />
                        <path d="M8 10.5h1v1H8v-1zm4.5 0h1v2h-1v-2z" fill="#0b57d0" />
                      </svg>
                    </div>
                    <div className="report-info">
                      <span className="report-title">Seguimento de Nó...</span>
                      <span className="report-meta">Assinado há 2h • Finalizado</span>
                    </div>
                    <MdKeyboardArrowRight className="report-arrow" />
                  </div>

                  <div className="report-card">
                    <div className="report-icon-wrapper">
                      <svg width="24" height="24" viewBox="0 0 24 24" fill="none" className="report-icon">
                        <path d="M19 3H5c-1.1 0-2 .9-2 2v14c0 1.1.9 2 2 2h14c1.1 0 2-.9 2-2V5c0-1.1-.9-2-2-2zm-9.5 8.5H8v1h1.5c.28 0 .5.22.5.5v1.5c0 .28-.22.5-.5.5H8v1H6.5v-6h3c.28 0 .5.22.5.5v1.5c0 .28-.22.5-.5.5zm4.5 1.5H12v-1h2c.28 0 .5-.22.5-.5V10c0-.28-.22-.5-.5-.5h-3v6h1.5v-2h1.5c.28 0 .5-.22.5-.5v-1c0-.28-.22-.5-.5-.5zm4-3.5h-3v6h1.5v-2h1.5v-1.5h-1.5v-1h1.5V9.5z" fill="#0b57d0" />
                        <path d="M8 10.5h1v1H8v-1zm4.5 0h1v2h-1v-2z" fill="#0b57d0" />
                      </svg>
                    </div>
                    <div className="report-info">
                      <span className="report-title">Fratura de Mão - M...</span>
                      <span className="report-meta">Assinado há 4h • Finalizado</span>
                    </div>
                    <MdKeyboardArrowRight className="report-arrow" />
                  </div>
                </div>
              </div>
            </div>

            {/* Right Column */}
            <div className="grid-right">
              {/* Ações Rápidas */}
              <div className="content-panel quick-actions-panel">
                <h2>Ações Rápidas</h2>
                <div className="quick-action-btns">
                  <button className="btn-action-large primary">
                    <MdAdd className="btn-icon" />
                    Novo Laudo
                  </button>
                  <button className="btn-action-large secondary">
                    <MdLibraryBooks className="btn-icon" />
                    Prontuários
                  </button>
                  <button className="btn-action-large secondary">
                    <MdLayers className="btn-icon" />
                    Modelos de Laudo
                  </button>
                </div>
              </div>


              {/* Modelos Favoritos (Placeholder based on design cutoff) */}
              <div className="content-panel mt-4">
                <h2>Modelos Favoritos</h2>
                <div className="favorites-list mt-3">
                  <p className="favorites-placeholder">Em breve modelos de laudos!</p>
                </div>
              </div>
            </div>
          </div>
        </main>
      </div>
    </div>
  );
};

export default Dashboard;
