// src/pages/Login/Login.jsx
import React, { useState, useEffect } from 'react';
import { useNavigate, useLocation } from 'react-router-dom';
import { MdVisibility, MdVisibilityOff, MdLock } from 'react-icons/md';
import SecurityBadges from '../../components/SecurityBadges/SecurityBadges';
import './Login.css';
import { apiLogin } from '../../api/login/apiLogin';
import { useAuthStore } from '../../store/useAuthStore';

const Login = () => {
  const navigate = useNavigate();
  const location = useLocation();
  const [showPassword, setShowPassword] = useState(false);
  const [warningMessage, setWarningMessage] = useState('');

  useEffect(() => {
    if (location.state && location.state.message) {
      setWarningMessage(location.state.message);
      window.history.replaceState({}, document.title);
    }
  }, [location]);

  const togglePasswordVisibility = () => {
    setShowPassword(!showPassword);
  };

  const handleSubmit = (e) => {
    e.preventDefault();
  };

  const handlelogin = async () => {
    const req = {
      email: document.getElementById('email').value,
      senha: document.getElementById('password').value,
    };

    try {
      const response = await apiLogin.login(req);
      const profile = await useAuthStore.getState().fetchProfile();
      navigate('/dashboard');
    } catch (error) {
      console.log(error);
    }
  }

  return (
    <div className="login-card-container">
      <div className="login-card">
        <div className="login-header">
          <h1>Login Seguro</h1>
          <p>Acesse seu painel médico profissional e prontuários de pacientes.</p>
        </div>

        {warningMessage && (
          <div className="login-warning-message">
            {warningMessage}
          </div>
        )}

        <form onSubmit={handleSubmit} className="login-form">
          <div className="form-group">
            <label htmlFor="email">E-mail Profissional</label>
            <input
              type="email"
              id="email"
              placeholder="medico@clinica.com"
              className="form-input"
            />
          </div>

          <div className="form-group">
            <div className="password-header">
              <label htmlFor="password">Senha</label>
              <a href="#forgot" className="forgot-password">Esqueceu a senha?</a>
            </div>
            <div className="password-input-wrapper">
              <input
                type={showPassword ? 'text' : 'password'}
                id="password"
                placeholder="••••••••"
                className="form-input password-input"
              />
              <button
                type="button"
                className="toggle-password-btn"
                onClick={togglePasswordVisibility}
                aria-label="Toggle password visibility"
              >
                {showPassword ? <MdVisibilityOff /> : <MdVisibility />}
              </button>
            </div>
          </div>

          <div className="form-group checkbox-group">
            <label className="checkbox-label">
              <input type="checkbox" className="custom-checkbox" />
              <span className="checkmark"></span>
              Manter conectado neste dispositivo
            </label>
          </div>

          <button type="submit" className="submit-btn" onClick={handlelogin}>
            <MdLock className="btn-icon" />
            Login Seguro
          </button>

          <div className="auth-switch-container" style={{ display: 'flex', justifyContent: 'center', gap: '0.5rem', marginTop: '1rem', fontSize: '0.875rem' }}>
            <span className="auth-switch-text" style={{ color: 'var(--text-gray)' }}>Não possui uma conta?</span>
            <button
              type="button"
              onClick={() => navigate('/cadastro')}
              className="auth-switch-btn"
              style={{ background: 'none', border: 'none', color: 'var(--primary-blue)', fontWeight: 600, cursor: 'pointer', padding: 0 }}
            >
              Cadastre-se
            </button>
          </div>
        </form>

        <SecurityBadges />
      </div>
    </div>
  );
};

export default Login;

// src/app/pages/login/login.component.ts
import { Component, inject, OnInit } from '@angular/core';
import { Router } from '@angular/router';
import { CommonModule } from '@angular/common';
import { FormsModule } from '@angular/forms';
import { SecurityBadgesComponent } from '../../components/security-badges/security-badges.component';
import { AuthApiService } from '../../core/services/api/auth-api.service';
import { AuthStore } from '../../core/services/store/auth.store';

@Component({
  selector: 'app-login',
  standalone: true,
  imports: [CommonModule, FormsModule, SecurityBadgesComponent],
  templateUrl: './login.component.html',
  styleUrls: ['./login.component.css']
})
export class LoginComponent implements OnInit {
  private router = inject(Router);
  private authApi = inject(AuthApiService);
  private authStore = inject(AuthStore);

  showPassword = false;
  warningMessage = '';
  
  email = '';
  senha = '';

  ngOnInit() {
    const navigation = this.router.getCurrentNavigation();
    if (navigation?.extras.state && navigation.extras.state['message']) {
      this.warningMessage = navigation.extras.state['message'];
    }
  }

  togglePasswordVisibility() {
    this.showPassword = !this.showPassword;
  }

  handleSubmit(e: Event) {
    e.preventDefault();
  }

  async handlelogin(e: Event) {
    e.preventDefault();
    if (!this.email || !this.senha) return;

    try {
      const response = await this.authApi.login({ email: this.email, senha: this.senha }).toPromise();
      console.log("retorno da api", response);
      await this.authStore.fetchProfile();
      this.router.navigate(['/dashboard']);
    } catch (error) {
      console.log(error);
      this.warningMessage = 'Erro ao realizar login. Verifique suas credenciais.';
    }
  }

  navigate(path: string) {
    this.router.navigate([path]);
  }
}

<div class="login-card-container">
  <div class="login-card">
    <div class="login-header">
      <h1>Login Seguro</h1>
      <p>Acesse seu painel médico profissional e prontuários de pacientes.</p>
    </div>

    @if (warningMessage) {
      <div class="login-warning-message">
        {{ warningMessage }}
      </div>
    }

    <form (submit)="handleSubmit($event)" class="login-form">
      <div class="form-group">
        <label for="email">E-mail Profissional</label>
        <input
          type="email"
          id="email"
          placeholder="medico@clinica.com"
          class="form-input"
          [(ngModel)]="email"
          name="email"
        />
      </div>

      <div class="form-group">
        <div class="password-header">
          <label for="password">Senha</label>
          <a href="#forgot" class="forgot-password">Esqueceu a senha?</a>
        </div>
        <div class="password-input-wrapper">
          <input
            [type]="showPassword ? 'text' : 'password'"
            id="password"
            placeholder="••••••••"
            class="form-input password-input"
            [(ngModel)]="senha"
            name="senha"
          />
          <button
            type="button"
            class="toggle-password-btn"
            (click)="togglePasswordVisibility()"
            aria-label="Toggle password visibility"
          >
            <span class="material-icons">{{ showPassword ? 'visibility_off' : 'visibility' }}</span>
          </button>
        </div>
      </div>

      <div class="form-group checkbox-group">
        <label class="checkbox-label">
          <input type="checkbox" class="custom-checkbox" />
          <span class="checkmark"></span>
          Manter conectado neste dispositivo
        </label>
      </div>

      <button type="submit" class="submit-btn" (click)="handlelogin($event)">
        <span class="material-icons btn-icon">lock</span>
        Login Seguro
      </button>

      <div class="auth-switch-container" style="display: flex; justify-content: center; gap: 0.5rem; margin-top: 1rem; font-size: 0.875rem;">
        <span class="auth-switch-text" style="color: var(--text-gray);">Não possui uma conta?</span>
        <button
          type="button"
          (click)="navigate('/cadastro')"
          class="auth-switch-btn"
          style="background: none; border: none; color: var(--primary-blue); font-weight: 600; cursor: pointer; padding: 0;"
        >
          Cadastre-se
        </button>
      </div>
    </form>

    <app-security-badges></app-security-badges>
  </div>
</div>
