// src/app/components/security-badges/security-badges.component.ts
import { Component } from '@angular/core';

@Component({
  selector: 'app-security-badges',
  imports: [],
  templateUrl: './security-badges.component.html',
  styleUrl: './security-badges.component.css'
})
export class SecurityBadgesComponent {

}

<div class="security-badges">
  <div class="badge badge-lgpd">
    <div class="badge-icon-wrapper green-bg">
      <svg class="badge-icon green-icon" stroke="currentColor" fill="currentColor" stroke-width="0" viewBox="0 0 24 24" height="1em" width="1em" xmlns="http://www.w3.org/2000/svg"><path fill="none" d="M0 0h24v24H0z"></path><path d="M12 1L3 5v6c0 5.55 3.84 10.74 9 12 5.16-1.26 9-6.45 9-12V5l-9-4zm-2 16l-4-4 1.41-1.41L10 14.17l6.59-6.59L18 9l-8 8z"></path></svg>
    </div>
    <div class="badge-text">
      <span class="badge-label">CERTIFICADO</span>
      <span class="badge-value">Conforme LGPD</span>
    </div>
  </div>
  
  <div class="badge badge-security">
    <div class="badge-icon-wrapper blue-bg">
      <svg class="badge-icon blue-icon" stroke="currentColor" fill="currentColor" stroke-width="0" viewBox="0 0 24 24" height="1em" width="1em" xmlns="http://www.w3.org/2000/svg"><path fill="none" d="M0 0h24v24H0V0z"></path><path d="M12 2L4 5v6.09c0 5.05 3.41 9.76 8 10.91 4.59-1.15 8-5.86 8-10.91V5l-8-3zm6 9.09c0 4-2.55 7.7-6 8.83-3.45-1.13-6-4.82-6-8.83v-4.7l6-2.25 6 2.25v4.7z"></path></svg>
    </div>
    <div class="badge-text">
      <span class="badge-label">SEGURANÇA</span>
      <span class="badge-value">AES-256 Bit</span>
    </div>
  </div>
</div>

// _react_backup/src/components/SecurityBadges/SecurityBadges.jsx
import React from 'react';
import { MdVerifiedUser, MdOutlineShield } from 'react-icons/md';
import './SecurityBadges.css';

const SecurityBadges = () => {
  return (
    <div className="security-badges">
      <div className="badge badge-lgpd">
        <div className="badge-icon-wrapper green-bg">
          <MdVerifiedUser className="badge-icon green-icon" />
        </div>
        <div className="badge-text">
          <span className="badge-label">CERTIFICADO</span>
          <span className="badge-value">Conforme LGPD</span>
        </div>
      </div>
      
      <div className="badge badge-security">
        <div className="badge-icon-wrapper blue-bg">
          <MdOutlineShield className="badge-icon blue-icon" />
        </div>
        <div className="badge-text">
          <span className="badge-label">SEGURANÇA</span>
          <span className="badge-value">AES-256 Bit</span>
        </div>
      </div>
    </div>
  );
};

export default SecurityBadges;
