// src/pages/CadastroPaciente/CadastroPaciente.jsx
import React, { useState } from 'react';
import { useNavigate, Link } from 'react-router-dom';
import { 
  MdDashboard, 
  MdPeople, 
  MdDescription, 
  MdCalendarToday, 
  MdSettings,
  MdPerson,
  MdPhone,
  MdLocationOn,
  MdCheckCircle
} from 'react-icons/md';
import './CadastroPaciente.css';
import { cadastrarPaciente } from '../../api/cadastroPaciente/apiCadastropaciente';
import { useAuthStore } from '../../store/useAuthStore';

const CadastroPaciente = () => {
  const user = useAuthStore((state) => state.user);
  const navigate = useNavigate();
  const [isSidebarOpen, setIsSidebarOpen] = useState(false);

  const [formData, setFormData] = useState({
    nomeCompleto: '', cpf: '', dataNascimento: '', genero: '',
    email: '', telefone: '', cep: '', logradouro: '',
    numero: '', complemento: '', bairro: '', cidade: '', estado: ''
  });
  const [formErrors, setFormErrors] = useState({});
  const [showSuccessPopup, setShowSuccessPopup] = useState(false);

  const formatCPF = (value) => value.replace(/\D/g, '').replace(/(\d{3})(\d)/, '$1.$2').replace(/(\d{3})(\d)/, '$1.$2').replace(/(\d{3})(\d{1,2})/, '$1-$2').replace(/(-\d{2})\d+?$/, '$1');
  const formatTelefone = (value) => value.replace(/\D/g, '').replace(/(\d{2})(\d)/, '($1) $2').replace(/(\d{5})(\d)/, '$1-$2').replace(/(-\d{4})\d+?$/, '$1');
  const formatDataNascimento = (value) => value.replace(/\D/g, '').replace(/(\d{2})(\d)/, '$1/$2').replace(/(\d{2})(\d)/, '$1/$2').replace(/(\/\d{4})\d+?$/, '$1');

  const handleCadastroPaciente = async () => {
    const requiredFields = [
      'nomeCompleto', 'cpf', 'dataNascimento', 'genero', 'email', 
      'telefone', 'cep', 'logradouro', 'numero', 'bairro', 'cidade', 'estado'
    ];
    
    const errors = {};
    let hasError = false;

    requiredFields.forEach(field => {
      if (!formData[field]) {
        errors[field] = 'Este campo é obrigatório';
        hasError = true;
      }
    });

    if (hasError) {
      setFormErrors(errors);
      return;
    }

    setFormErrors({});

    try {
      let dataToSend = null;
      if (formData.dataNascimento.length === 10) {
        const [dia, mes, ano] = formData.dataNascimento.split('/');
        dataToSend = new Date(Number(ano), Number(mes) - 1, Number(dia));
      }

    const payload = {
      nomeCompleto: formData.nomeCompleto,
      cpf: formData.cpf,
      dataNascimento: dataToSend,
      telefone: formData.telefone
    };

    await cadastrarPaciente(payload);
      setShowSuccessPopup(true);
    setFormData({ nomeCompleto: '', cpf: '', dataNascimento: '', telefone: '', genero: '', email: '', cep: '', logradouro: '', numero: '', complemento: '', bairro: '', cidade: '', estado: ''   });
    } catch (error) {
      console.error("Erro ao cadastrar paciente:", error);
    }
  }

const closePopupAndNavigate = () => {
  setShowSuccessPopup(false);
  navigate('/pacientes');
};

  return (
    <div className="dashboard-container">
      {/* Mobile Sidebar Overlay */}
      {isSidebarOpen && (
        <div 
          className="sidebar-overlay" 
          onClick={() => setIsSidebarOpen(false)}
        ></div>
      )}

      {/* Sidebar */}
      <aside className={`dashboard-sidebar ${isSidebarOpen ? 'open' : ''}`}>
        <div className="sidebar-header">
          <div className="sidebar-logo">
            <svg width="24" height="24" viewBox="0 0 24 24" fill="none" xmlns="http://www.w3.org/2000/svg" className="logo-icon">
              <path d="M12 2L2 12l10 10 10-10L12 2z" fill="currentColor" />
              <path d="M12 2L2 12l10 10V2z" fill="#0b57d0" />
              <path d="M12 2l10 10-10 10V2z" fill="#1a73e8" />
            </svg>
            <span className="logo-text">Tila Medical</span>
          </div>
        </div>

        <nav className="sidebar-nav">
          <ul className="nav-list">
            <li className="nav-item" onClick={() => navigate('/dashboard')}>
              <MdDashboard className="nav-icon" />
              <span>Painel</span>
            </li>
            <li className="nav-item active" onClick={() => navigate('/pacientes')}>
              <MdPeople className="nav-icon" />
              <span>Pacientes</span>
            </li>
            <li className="nav-item">
              <MdDescription className="nav-icon" />
              <span>Laudos</span>
            </li>
            <li className="nav-item">
              <MdCalendarToday className="nav-icon" />
              <span>Agenda</span>
            </li>
          </ul>
        </nav>

        <div className="sidebar-footer">
          <div className="nav-item settings-item">
            <MdSettings className="nav-icon" />
            <span>Configurações</span>
          </div>
          <div className="user-profile">
            <div className="user-avatar">
              <img src="https://ui-avatars.com/api/?name=Julian+Smith&background=0D8ABC&color=fff" alt="Dr. Julian Smith" />
            </div>
            <div className="user-info">
              <span className="user-name">{user?.nomeCompleto}</span>
              <span className="user-role">{user?.especialidade}</span>
            </div>
          </div>
        </div>
      </aside>

      {/* Main Content Area */}
      <div className="dashboard-main bg-light">
        {/* Top Header Placeholder / Mobile Toggle */}
        <header className="dashboard-header header-cadastro">
          <button 
            className="mobile-menu-btn" 
            onClick={() => setIsSidebarOpen(true)}
            aria-label="Abrir Menu"
          >
            <svg width="24" height="24" viewBox="0 0 24 24"><path fill="currentColor" d="M3 18h18v-2H3v2zm0-5h18v-2H3v2zm0-7v2h18V6H3z"></path></svg>
          </button>
        </header>

        {/* Cadastro Content */}
        <main className="cadastro-content">
          <div className="breadcrumbs">
            <Link to="/pacientes" className="breadcrumb-link">Pacientes</Link>
            <span className="breadcrumb-separator">›</span>
            <span className="breadcrumb-current">Cadastrar Novo Paciente</span>
          </div>

          <div className="page-header">
            <h1>Cadastrar Novo Paciente</h1>
            <p className="page-subtitle">Insira as informações detalhadas para registrar um novo paciente no banco de dados da clínica.</p>
          </div>
          
          <form className="cadastro-form" onSubmit={(e) => e.preventDefault()}>
            <section className="form-section">
              <div className="section-header">
                <MdPerson className="section-icon feature-icon" />
                <h2>Dados Pessoais</h2>
              </div>
              <div className="form-grid">
                <div className="form-group col-span-2">
                  <label>Nome Completo *</label>
                  <input type="text" placeholder="Ex: Maria Oliveira" value={formData.nomeCompleto} onChange={(e) => setFormData({...formData, nomeCompleto: e.target.value})} className={formErrors.nomeCompleto ? 'input-error' : ''} />
                  {formErrors.nomeCompleto && <span className="error-text">{formErrors.nomeCompleto}</span>}
                </div>
                <div className="form-group">
                  <label>CPF *</label>
                  <input type="text" placeholder="000.000.000-00" value={formData.cpf} onChange={(e) => setFormData({...formData, cpf: formatCPF(e.target.value)})} className={formErrors.cpf ? 'input-error' : ''} />
                  {formErrors.cpf && <span className="error-text">{formErrors.cpf}</span>}
                </div>
                <div className="form-group">
                  <label>Data de Nascimento *</label>
                  <div className="input-with-icon">
                    <input type="text" placeholder="DD/MM/AAAA" value={formData.dataNascimento} onChange={(e) => setFormData({...formData, dataNascimento: formatDataNascimento(e.target.value)})} className={formErrors.dataNascimento ? 'input-error' : ''} />
                    <MdCalendarToday className="inner-icon" />
                  </div>
                  {formErrors.dataNascimento && <span className="error-text">{formErrors.dataNascimento}</span>}
                </div>
                <div className="form-group">
                  <label>Gênero *</label>
                  <div className="select-wrapper">
                    <select value={formData.genero} onChange={(e) => setFormData({...formData, genero: e.target.value})} className={formErrors.genero ? 'input-error' : ''}>
                      <option value="" disabled>Selecione</option>
                      <option value="M">Masculino</option>
                      <option value="F">Feminino</option>
                      <option value="O">Outro</option>
                    </select>
                  </div>
                  {formErrors.genero && <span className="error-text">{formErrors.genero}</span>}
                </div>
              </div>
            </section>

            <section className="form-section">
              <div className="section-header">
                <MdPhone className="section-icon feature-icon" />
                <h2>Contato</h2>
              </div>
              <div className="form-grid">
                <div className="form-group col-span-2">
                  <label>E-mail *</label>
                  <input type="email" placeholder="paciente@exemplo.com" value={formData.email} onChange={(e) => setFormData({...formData, email: e.target.value})} className={formErrors.email ? 'input-error' : ''} />
                  {formErrors.email && <span className="error-text">{formErrors.email}</span>}
                </div>
                <div className="form-group col-span-2">
                  <label>Telefone / WhatsApp *</label>
                  <input type="text" placeholder="(00) 00000-0000" value={formData.telefone} onChange={(e) => setFormData({...formData, telefone: formatTelefone(e.target.value)})} className={formErrors.telefone ? 'input-error' : ''} />
                  {formErrors.telefone && <span className="error-text">{formErrors.telefone}</span>}
                </div>
              </div>
            </section>

            <section className="form-section">
              <div className="section-header">
                <MdLocationOn className="section-icon feature-icon" />
                <h2>Endereço</h2>
              </div>
              <div className="form-grid">
                <div className="form-group">
                  <label>CEP *</label>
                  <input type="text" placeholder="00000-000" value={formData.cep} onChange={(e) => setFormData({...formData, cep: e.target.value})} className={formErrors.cep ? 'input-error' : ''} />
                  {formErrors.cep && <span className="error-text">{formErrors.cep}</span>}
                </div>
                <div className="form-group col-span-3">
                  <label>Logradouro *</label>
                  <input type="text" placeholder="Rua, Avenida, etc." value={formData.logradouro} onChange={(e) => setFormData({...formData, logradouro: e.target.value})} className={formErrors.logradouro ? 'input-error' : ''} />
                  {formErrors.logradouro && <span className="error-text">{formErrors.logradouro}</span>}
                </div>
                <div className="form-group">
                  <label>Número *</label>
                  <input type="text" placeholder="123" value={formData.numero} onChange={(e) => setFormData({...formData, numero: e.target.value})} className={formErrors.numero ? 'input-error' : ''} />
                  {formErrors.numero && <span className="error-text">{formErrors.numero}</span>}
                </div>
                <div className="form-group col-span-2">
                  <label>Complemento</label>
                  <input type="text" placeholder="Apto, Bloco, etc." value={formData.complemento} onChange={(e) => setFormData({...formData, complemento: e.target.value})} />
                </div>
                <div className="form-group">
                  <label>Bairro *</label>
                  <input type="text" placeholder="Nome do bairro" value={formData.bairro} onChange={(e) => setFormData({...formData, bairro: e.target.value})} className={formErrors.bairro ? 'input-error' : ''} />
                  {formErrors.bairro && <span className="error-text">{formErrors.bairro}</span>}
                </div>
                <div className="form-group col-span-2">
                  <label>Cidade *</label>
                  <input type="text" placeholder="Nome da cidade" value={formData.cidade} onChange={(e) => setFormData({...formData, cidade: e.target.value})} className={formErrors.cidade ? 'input-error' : ''} />
                  {formErrors.cidade && <span className="error-text">{formErrors.cidade}</span>}
                </div>
                <div className="form-group">
                  <label>Estado *</label>
                  <div className="select-wrapper">
                    <select value={formData.estado} onChange={(e) => setFormData({...formData, estado: e.target.value})} className={formErrors.estado ? 'input-error' : ''}>
                      <option value="" disabled>UF</option>
                      <option value="AC">AC</option>
                      <option value="AL">AL</option>
                      <option value="AP">AP</option>
                      <option value="AM">AM</option>
                      <option value="BA">BA</option>
                      <option value="CE">CE</option>
                      <option value="DF">DF</option>
                      <option value="ES">ES</option>
                      <option value="GO">GO</option>
                      <option value="MA">MA</option>
                      <option value="MT">MT</option>
                      <option value="MS">MS</option>
                      <option value="MG">MG</option>
                      <option value="PA">PA</option>
                      <option value="PB">PB</option>
                      <option value="PR">PR</option>
                      <option value="PE">PE</option>
                      <option value="PI">PI</option>
                      <option value="RJ">RJ</option>
                      <option value="RN">RN</option>
                      <option value="RS">RS</option>
                      <option value="RO">RO</option>
                      <option value="RR">RR</option>
                      <option value="SC">SC</option>
                      <option value="SP">SP</option>
                      <option value="SE">SE</option>
                      <option value="TO">TO</option>
                    </select>
                  </div>
                  {formErrors.estado && <span className="error-text">{formErrors.estado}</span>}
                </div>
              </div>
            </section>

            <div className="form-actions">
              <button type="button" className="btn-cancelar" onClick={() => navigate('/pacientes')}>Cancelar</button>
              <button type="submit" className="btn-cadastrar" onClick={handleCadastroPaciente}>Cadastrar Paciente</button>
            </div>
          </form>
        </main>
      </div>

      {/* Success Popup */}
      {showSuccessPopup && (
        <div className="popup-overlay">
          <div className="popup-content">
            <MdCheckCircle className="popup-icon" />
            <h2>Cadastro Realizado!</h2>
            <p>O paciente foi cadastrado com sucesso no sistema.</p>
            <button className="btn-popup-ok" onClick={closePopupAndNavigate}>
              Continuar
            </button>
          </div>
        </div>
      )}
    </div>
  );
};

export default CadastroPaciente;

// src/app/pages/cadastro-paciente/cadastro-paciente.component.ts
import { Component, inject } from '@angular/core';
import { CommonModule } from '@angular/common';
import { FormsModule } from '@angular/forms';
import { Router, RouterLink } from '@angular/router';
import { AuthStore } from '../../core/services/store/auth.store';
import { PacienteApiService } from '../../core/services/api/paciente-api.service';

@Component({
  selector: 'app-cadastro-paciente',
  standalone: true,
  imports: [CommonModule, FormsModule, RouterLink],
  templateUrl: './cadastro-paciente.component.html',
  styleUrls: ['./cadastro-paciente.component.css']
})
export class CadastroPacienteComponent {
  private router = inject(Router);
  private authStore = inject(AuthStore);
  private pacienteApi = inject(PacienteApiService);

  user = this.authStore.user;
  isSidebarOpen = false;

  formData: any = {
    nomeCompleto: '', cpf: '', dataNascimento: '', genero: '',
    email: '', telefone: '', cep: '', logradouro: '',
    numero: '', complemento: '', bairro: '', cidade: '', estado: ''
  };

  formErrors: any = {};
  showSuccessPopup = false;

  setIsSidebarOpen(isOpen: boolean) {
    this.isSidebarOpen = isOpen;
  }

  navigate(path: string) {
    this.router.navigate([path]);
  }

  formatCPF(value: string) {
    return value.replace(/\D/g, '')
                .replace(/(\d{3})(\d)/, '$1.$2')
                .replace(/(\d{3})(\d)/, '$1.$2')
                .replace(/(\d{3})(\d{1,2})/, '$1-$2')
                .replace(/(-\d{2})\d+?$/, '$1');
  }

  formatTelefone(value: string) {
    return value.replace(/\D/g, '')
                .replace(/(\d{2})(\d)/, '($1) $2')
                .replace(/(\d{5})(\d)/, '$1-$2')
                .replace(/(-\d{4})\d+?$/, '$1');
  }

  formatDataNascimento(value: string) {
    return value.replace(/\D/g, '')
                .replace(/(\d{2})(\d)/, '$1/$2')
                .replace(/(\d{2})(\d)/, '$1/$2')
                .replace(/(\/\d{4})\d+?$/, '$1');
  }

  onCPFChange(value: string) {
    this.formData.cpf = this.formatCPF(value);
  }

  onTelefoneChange(value: string) {
    this.formData.telefone = this.formatTelefone(value);
  }

  onDataNascimentoChange(value: string) {
    this.formData.dataNascimento = this.formatDataNascimento(value);
  }

  handleSubmit(e: Event) {
    e.preventDefault();
  }

  async handleCadastroPaciente() {
    const requiredFields = [
      'nomeCompleto', 'cpf', 'dataNascimento', 'genero', 'email', 
      'telefone', 'cep', 'logradouro', 'numero', 'bairro', 'cidade', 'estado'
    ];
    
    const errors: any = {};
    let hasError = false;

    requiredFields.forEach(field => {
      if (!this.formData[field]) {
        errors[field] = 'Este campo é obrigatório';
        hasError = true;
      }
    });

    if (hasError) {
      this.formErrors = errors;
      return;
    }

    this.formErrors = {};

    try {
      let dataToSend: Date | null = null;
      if (this.formData.dataNascimento.length === 10) {
        const [dia, mes, ano] = this.formData.dataNascimento.split('/');
        dataToSend = new Date(Number(ano), Number(mes) - 1, Number(dia));
      }

      const payload: any = {
        nomeCompleto: this.formData.nomeCompleto,
        cpf: this.formData.cpf,
        dataNascimento: dataToSend,
        telefone: this.formData.telefone,
        // others can be added if backend supports
      };

      await this.pacienteApi.cadastrarPaciente(payload).toPromise();
      this.showSuccessPopup = true;
      
      this.formData = { 
        nomeCompleto: '', cpf: '', dataNascimento: '', genero: '', 
        email: '', telefone: '', cep: '', logradouro: '', numero: '', 
        complemento: '', bairro: '', cidade: '', estado: '' 
      };
    } catch (error) {
      console.error("Erro ao cadastrar paciente:", error);
    }
  }

  closePopupAndNavigate() {
    this.showSuccessPopup = false;
    this.router.navigate(['/pacientes']);
  }
}

<div class="dashboard-container">
  <!-- Mobile Sidebar Overlay -->
  @if (isSidebarOpen) {
    <div class="sidebar-overlay" (click)="setIsSidebarOpen(false)"></div>
  }

  <!-- Sidebar -->
  <aside class="dashboard-sidebar" [class.open]="isSidebarOpen">
    <div class="sidebar-header">
      <div class="sidebar-logo">
        <svg width="24" height="24" viewBox="0 0 24 24" fill="none" class="logo-icon">
          <path d="M12 2L2 12l10 10 10-10L12 2z" fill="currentColor" />
          <path d="M12 2L2 12l10 10V2z" fill="#0b57d0" />
          <path d="M12 2l10 10-10 10V2z" fill="#1a73e8" />
        </svg>
        <span class="logo-text">Tila Medical</span>
      </div>
    </div>

    <nav class="sidebar-nav">
      <ul class="nav-list">
        <li class="nav-item" routerLink="/dashboard">
          <span class="material-icons nav-icon">dashboard</span>
          <span>Painel</span>
        </li>
        <li class="nav-item active" routerLink="/pacientes">
          <span class="material-icons nav-icon">people</span>
          <span>Pacientes</span>
        </li>
        <li class="nav-item">
          <span class="material-icons nav-icon">description</span>
          <span>Laudos</span>
        </li>
        <li class="nav-item">
          <span class="material-icons nav-icon">calendar_today</span>
          <span>Agenda</span>
        </li>
      </ul>
    </nav>

    <div class="sidebar-footer">
      <div class="nav-item settings-item">
        <span class="material-icons nav-icon">settings</span>
        <span>Configurações</span>
      </div>
      <div class="user-profile">
        <div class="user-avatar">
          <img src="https://ui-avatars.com/api/?name=Julian+Smith&background=0D8ABC&color=fff" alt="Dr." />
        </div>
        <div class="user-info">
          <span class="user-name">{{ user()?.nomeCompleto }}</span>
          <span class="user-role">{{ user()?.especialidade }}</span>
        </div>
      </div>
    </div>
  </aside>

  <!-- Main Content Area -->
  <div class="dashboard-main bg-light">
    <!-- Top Header Placeholder / Mobile Toggle -->
    <header class="dashboard-header header-cadastro">
      <button class="mobile-menu-btn" (click)="setIsSidebarOpen(true)" aria-label="Abrir Menu">
        <svg width="24" height="24" viewBox="0 0 24 24"><path fill="currentColor" d="M3 18h18v-2H3v2zm0-5h18v-2H3v2zm0-7v2h18V6H3z"></path></svg>
      </button>
    </header>

    <!-- Cadastro Content -->
    <main class="cadastro-content">
      <div class="breadcrumbs">
        <a routerLink="/pacientes" class="breadcrumb-link">Pacientes</a>
        <span class="breadcrumb-separator">›</span>
        <span class="breadcrumb-current">Cadastrar Novo Paciente</span>
      </div>

      <div class="page-header">
        <h1>Cadastrar Novo Paciente</h1>
        <p class="page-subtitle">Insira as informações detalhadas para registrar um novo paciente no banco de dados da clínica.</p>
      </div>
      
      <form class="cadastro-form" (submit)="handleSubmit($event)">
        <section class="form-section">
          <div class="section-header">
            <span class="material-icons section-icon feature-icon">person</span>
            <h2>Dados Pessoais</h2>
          </div>
          <div class="form-grid">
            <div class="form-group col-span-2">
              <label>Nome Completo *</label>
              <input type="text" placeholder="Ex: Maria Oliveira" [(ngModel)]="formData.nomeCompleto" name="nomeCompleto" [class.input-error]="formErrors['nomeCompleto']" />
              @if (formErrors['nomeCompleto']) { <span class="error-text">{{formErrors['nomeCompleto']}}</span> }
            </div>
            <div class="form-group">
              <label>CPF *</label>
              <input type="text" placeholder="000.000.000-00" [ngModel]="formData.cpf" (ngModelChange)="onCPFChange($event)" name="cpf" [class.input-error]="formErrors['cpf']" />
              @if (formErrors['cpf']) { <span class="error-text">{{formErrors['cpf']}}</span> }
            </div>
            <div class="form-group">
              <label>Data de Nascimento *</label>
              <div class="input-with-icon">
                <input type="text" placeholder="DD/MM/AAAA" [ngModel]="formData.dataNascimento" (ngModelChange)="onDataNascimentoChange($event)" name="dataNascimento" [class.input-error]="formErrors['dataNascimento']" />
                <span class="material-icons inner-icon">calendar_today</span>
              </div>
              @if (formErrors['dataNascimento']) { <span class="error-text">{{formErrors['dataNascimento']}}</span> }
            </div>
            <div class="form-group">
              <label>Gênero *</label>
              <div class="select-wrapper">
                <select [(ngModel)]="formData.genero" name="genero" [class.input-error]="formErrors['genero']">
                  <option value="" disabled>Selecione</option>
                  <option value="M">Masculino</option>
                  <option value="F">Feminino</option>
                  <option value="O">Outro</option>
                </select>
              </div>
              @if (formErrors['genero']) { <span class="error-text">{{formErrors['genero']}}</span> }
            </div>
          </div>
        </section>

        <section class="form-section">
          <div class="section-header">
            <span class="material-icons section-icon feature-icon">phone</span>
            <h2>Contato</h2>
          </div>
          <div class="form-grid">
            <div class="form-group col-span-2">
              <label>E-mail *</label>
              <input type="email" placeholder="paciente@exemplo.com" [(ngModel)]="formData.email" name="email" [class.input-error]="formErrors['email']" />
              @if (formErrors['email']) { <span class="error-text">{{formErrors['email']}}</span> }
            </div>
            <div class="form-group col-span-2">
              <label>Telefone / WhatsApp *</label>
              <input type="text" placeholder="(00) 00000-0000" [ngModel]="formData.telefone" (ngModelChange)="onTelefoneChange($event)" name="telefone" [class.input-error]="formErrors['telefone']" />
              @if (formErrors['telefone']) { <span class="error-text">{{formErrors['telefone']}}</span> }
            </div>
          </div>
        </section>

        <section class="form-section">
          <div class="section-header">
            <span class="material-icons section-icon feature-icon">location_on</span>
            <h2>Endereço</h2>
          </div>
          <div class="form-grid">
            <div class="form-group">
              <label>CEP *</label>
              <input type="text" placeholder="00000-000" [(ngModel)]="formData.cep" name="cep" [class.input-error]="formErrors['cep']" />
              @if (formErrors['cep']) { <span class="error-text">{{formErrors['cep']}}</span> }
            </div>
            <div class="form-group col-span-3">
              <label>Logradouro *</label>
              <input type="text" placeholder="Rua, Avenida, etc." [(ngModel)]="formData.logradouro" name="logradouro" [class.input-error]="formErrors['logradouro']" />
              @if (formErrors['logradouro']) { <span class="error-text">{{formErrors['logradouro']}}</span> }
            </div>
            <div class="form-group">
              <label>Número *</label>
              <input type="text" placeholder="123" [(ngModel)]="formData.numero" name="numero" [class.input-error]="formErrors['numero']" />
              @if (formErrors['numero']) { <span class="error-text">{{formErrors['numero']}}</span> }
            </div>
            <div class="form-group col-span-2">
              <label>Complemento</label>
              <input type="text" placeholder="Apto, Bloco, etc." [(ngModel)]="formData.complemento" name="complemento" />
            </div>
            <div class="form-group">
              <label>Bairro *</label>
              <input type="text" placeholder="Nome do bairro" [(ngModel)]="formData.bairro" name="bairro" [class.input-error]="formErrors['bairro']" />
              @if (formErrors['bairro']) { <span class="error-text">{{formErrors['bairro']}}</span> }
            </div>
            <div class="form-group col-span-2">
              <label>Cidade *</label>
              <input type="text" placeholder="Nome da cidade" [(ngModel)]="formData.cidade" name="cidade" [class.input-error]="formErrors['cidade']" />
              @if (formErrors['cidade']) { <span class="error-text">{{formErrors['cidade']}}</span> }
            </div>
            <div class="form-group">
              <label>Estado *</label>
              <div class="select-wrapper">
                <select [(ngModel)]="formData.estado" name="estado" [class.input-error]="formErrors['estado']">
                  <option value="" disabled>UF</option>
                  <option value="AC">AC</option>
                  <option value="AL">AL</option>
                  <option value="AP">AP</option>
                  <option value="AM">AM</option>
                  <option value="BA">BA</option>
                  <option value="CE">CE</option>
                  <option value="DF">DF</option>
                  <option value="ES">ES</option>
                  <option value="GO">GO</option>
                  <option value="MA">MA</option>
                  <option value="MT">MT</option>
                  <option value="MS">MS</option>
                  <option value="MG">MG</option>
                  <option value="PA">PA</option>
                  <option value="PB">PB</option>
                  <option value="PR">PR</option>
                  <option value="PE">PE</option>
                  <option value="PI">PI</option>
                  <option value="RJ">RJ</option>
                  <option value="RN">RN</option>
                  <option value="RS">RS</option>
                  <option value="RO">RO</option>
                  <option value="RR">RR</option>
                  <option value="SC">SC</option>
                  <option value="SP">SP</option>
                  <option value="SE">SE</option>
                  <option value="TO">TO</option>
                </select>
              </div>
              @if (formErrors['estado']) { <span class="error-text">{{formErrors['estado']}}</span> }
            </div>
          </div>
        </section>

        <div class="form-actions">
          <button type="button" class="btn-cancelar" (click)="navigate('/pacientes')">Cancelar</button>
          <button type="button" class="btn-cadastrar" (click)="handleCadastroPaciente()">Cadastrar Paciente</button>
        </div>
      </form>
    </main>
  </div>

  <!-- Success Popup -->
  @if (showSuccessPopup) {
    <div class="popup-overlay">
      <div class="popup-content">
        <span class="material-icons popup-icon">check_circle</span>
        <h2>Cadastro Realizado!</h2>
        <p>O paciente foi cadastrado com sucesso no sistema.</p>
        <button class="btn-popup-ok" (click)="closePopupAndNavigate()">
          Continuar
        </button>
      </div>
    </div>
  }
</div>
